language: go
go:
 - 1.5
 - release
 - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
 
 
script:
  - $HOME/gopath/bin/goveralls -coverprofile= -v -repotoken wW2PpiBbqtJ8BoUqMA7P4ZZsBGyurVXpx
